Add css course files
Unosquare-CoE-JavaScript/camilo-kowsniowski pull request #14
Opened 2022-07-01 18:57 UTC by kosniowskiunosquare

Adding css finished files

2022-07-25 19:53 UTC, alexeikmun requested changes

2022-07-25 19:53 UTC, alexeikmun commented on starwars/swapi/src/App.jsx
> +      <header class='Background'>
Use className because it's a React standard

2022-07-25 19:53 UTC, alexeikmun commented on starwars/swapi/src/components/Home.jsx
> +  return <div class='home_background'></div>;
Same here: className

2022-07-25 19:53 UTC, alexeikmun commented on starwars/swapi/src/components/Planets.jsx
> -          <div key={i}>
Don't use map indexes as a `key`, use `planet.id` or any other unique key

2022-07-25 19:53 UTC, alexeikmun commented on starwars/swapi/src/components/Planets.jsx
> -            <p>{people.height}</p> */}
Remove commented code

2022-07-25 19:53 UTC, alexeikmun commented on starwars/swapi/src/components/Planets.jsx
> +                  {' '}
Please use white spaces o HTML identitiy: `&nbsp;` instead of  `{' '}`

2022-07-25 19:53 UTC, alexeikmun commented on starwars/swapi/src/components/Planets.jsx
> +                  <span class='card-text-data'>Name: {planets.name}</span>
Rename `planets` object as singlular: `planet`

2022-07-25 19:55 UTC, alexeikmun requested changes

2022-07-25 19:55 UTC, alexeikmun commented on starwars/swapi/src/components/Planets.jsx
> +              <div class='cards' key={i}>
Don't use map indexes as a `key`, use `planet.id` or any other unique key

2022-07-25 19:56 UTC, alexeikmun commented on starwars/swapi/src/components/Home.jsx
> +  return <div class='home_background'></div>;
And the entire document

2022-07-26 20:31 UTC, kosniowskiunosquare commented on Practice React Project/src/index.js
> +    clientId='TUgQSAy7YvgUuSay2pz4oTPn45Ynm4NY'
solved

2022-07-26 21:09 UTC, kosniowskiunosquare commented on starwars/swapi/src/components/Home.jsx
> +  return <div class='home_background'></div>;
fixed in the entire document

2022-11-15 19:54 UTC, merged