Starwars
Unosquare-CoE-JavaScript/camilo-kowsniowski pull request #15
Opened 2022-07-15 20:28 UTC by kosniowskiunosquare

Added folder organization

2022-07-15 21:33 UTC, alexeikmun requested changes

2022-07-15 21:33 UTC, alexeikmun commented on starwars/swapi/src/App.jsx
> +      let res = await fetch('https://swapi.dev/api/planets/?format=json');
It would be nice to refactor the URL `https://swapi.dev` into a single variable like `baseName` then add it to the rest of URI

2022-07-19 19:18 UTC, kosniowskiunosquare commented on starwars/swapi/src/components/Planets.jsx
> +                  {' '}
Solved

2022-07-19 19:20 UTC, kosniowskiunosquare commented on starwars/swapi/src/App.jsx
> +      let res = await fetch('https://swapi.dev/api/planets/?format=json');
Im working on that but i have some problems,  i think this maybe its the solution 

`  async function fetchData() {
      let baseName = await fetch('https://swapi.dev/api');
      let resPeople = await fetch(baseName + 'people/?format=json');
      let resPlanets = await fetch(baseName + 'planets/?format=json');
      let data1 = await resPeople.json();
      let data2 = await resPlanets.json();

      setFecthData(data1.results);
      setFecthData(data2.results);
    }`

2022-07-19 19:56 UTC, alexeikmun commented on starwars/swapi/src/App.jsx
> +      let res = await fetch('https://swapi.dev/api/planets/?format=json');
I suggest something simpler as follows:

```js
async function fetchData(uri) {
    const response = await fetch(`https://swapi.dev/api/${uri}?format=json`);
    return response.json()
}

const planets = await fetchData('planets');
const people = fetchData('people');
```

2022-11-15 19:57 UTC, merged